#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 14 01:58:41 CEST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim pl_eth_10g_wrapper_behav -key {Behavioral:sim_1:Functional:pl_eth_10g_wrapper} -tclbatch pl_eth_10g_wrapper.tcl -protoinst "protoinst_files/pl_eth_10g.protoinst" -log simulate.log"
xsim pl_eth_10g_wrapper_behav -key {Behavioral:sim_1:Functional:pl_eth_10g_wrapper} -tclbatch pl_eth_10g_wrapper.tcl -protoinst "protoinst_files/pl_eth_10g.protoinst" -log simulate.log

