#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : pl_eth_10g.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Oct 14 01:55:46 CEST 2022
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: pl_eth_10g.sh [-help]
# usage: pl_eth_10g.sh [-lib_map_path]
# usage: pl_eth_10g.sh [-noclean_files]
# usage: pl_eth_10g.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'pl_eth_10g.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm lib_pkg_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_22 axi_sg_v4_1_13 axi_dma_v7_1_21 xil_defaultlib util_vector_logic_v2_0_1 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_2 xlconstant_v1_1_6 gtwizard_ultrascale_v1_7_7 xxv_ethernet_v3_1_0 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_20 axi_data_fifo_v2_1_19 axi_crossbar_v2_1_21 axi_protocol_converter_v2_1_20 axi_clock_converter_v2_1_19 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_20 axi_mmu_v2_1_18 proc_sys_reset_v5_0_13 xlconcat_v2_1_3 axi_vip_v1_1_6 zynq_ultra_ps_e_vip_v1_0_6)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "pl_eth_10g.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_22 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/1e40/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_21 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec2a/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_axi_dma_0_0/sim/pl_eth_10g_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_dma_rx_rst_0/sim/pl_eth_10g_dma_rx_rst_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_dma_tx_rst_0/sim/pl_eth_10g_dma_tx_rst_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/3341/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_rx_data_fifo_0/sim/pl_eth_10g_rx_data_fifo_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_rx_rst_n_0/sim/pl_eth_10g_rx_rst_n_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_sfp_tx_dis_0/sim/pl_eth_10g_sfp_tx_dis_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_tx_data_fifo_0/sim/pl_eth_10g_tx_data_fifo_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_tx_rst_n_0/sim/pl_eth_10g_tx_rst_n_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_0_0/sim/pl_eth_10g_xlconstant_0_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_1_0/sim/pl_eth_10g_xlconstant_1_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_2_0/sim/pl_eth_10g_xlconstant_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work gtwizard_ultrascale_v1_7_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/sim/pl_eth_10g_xxv_ethernet_0_0_gt_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/sim/pl_eth_10g_xxv_ethernet_0_0_gt_gtwizard_gthe4.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/sim/pl_eth_10g_xxv_ethernet_0_0_gt_gtwizard_top.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/sim/pl_eth_10g_xxv_ethernet_0_0_gt.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_wrapper.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_top.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_axi4_lite_if_wrapper.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0/gtwizard_ultrascale_v1_7_gthe4_common.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0_gt_gthe4_common_wrapper.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_common_wrapper.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_ultrascale_rx_userclk.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_ultrascale_tx_userclk.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xxv_ethernet_v3_1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/4caa/hdl/xxv_ethernet_v3_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xbar_0/sim/pl_eth_10g_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/9e81/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/d394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_us_0/sim/pl_eth_10g_auto_us_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_us_1/sim/pl_eth_10g_auto_us_1.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_0/sim/pl_eth_10g_auto_cc_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_us_2/sim/pl_eth_10g_auto_us_2.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_1/sim/pl_eth_10g_auto_cc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_mmu_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/cba0/hdl/axi_mmu_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_s00_mmu_0/sim/pl_eth_10g_s00_mmu_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_s01_mmu_0/sim/pl_eth_10g_s01_mmu_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_s02_mmu_0/sim/pl_eth_10g_s02_mmu_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xbar_1/sim/pl_eth_10g_xbar_1.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_0/sim/pl_eth_10g_auto_ds_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_0/sim/pl_eth_10g_auto_pc_0.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_1/sim/pl_eth_10g_auto_ds_1.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_1/sim/pl_eth_10g_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_rst_ps8_0_99M_0/sim/pl_eth_10g_rst_ps8_0_99M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_util_vector_logic_0_0/sim/pl_eth_10g_util_vector_logic_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconcat_0_0/sim/pl_eth_10g_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/dc12/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/header_files" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"/tools/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/sim/pl_eth_10g_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
    "$ref_dir/../../../../pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/sim/pl_eth_10g.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.pl_eth_10g xil_defaultlib.glbl -o pl_eth_10g_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./pl_eth_10g_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./pl_eth_10g.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key pl_eth_10g_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc pl_eth_10g_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./pl_eth_10g.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: pl_eth_10g.sh [-help]\n\
Usage: pl_eth_10g.sh [-lib_map_path]\n\
Usage: pl_eth_10g.sh [-reset_run]\n\
Usage: pl_eth_10g.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
