# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-53963-supersonic/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xczu9eg-ffvb1156-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl
    /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl
  } {
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/4caa/hdl/xxv_ethernet_v3_1_vl_rfs.sv
      /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl
    /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl
  } {
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_dma_rx_rst_0/synth/pl_eth_10g_dma_rx_rst_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_dma_tx_rst_0/synth/pl_eth_10g_dma_tx_rst_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/3341/hdl/axis_data_fifo_v2_0_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_rx_data_fifo_0/synth/pl_eth_10g_rx_data_fifo_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_rx_rst_n_0/synth/pl_eth_10g_rx_rst_n_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_sfp_tx_dis_0/synth/pl_eth_10g_sfp_tx_dis_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_tx_data_fifo_0/synth/pl_eth_10g_tx_data_fifo_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_tx_rst_n_0/synth/pl_eth_10g_tx_rst_n_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_0_0/synth/pl_eth_10g_xlconstant_0_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_1_0/synth/pl_eth_10g_xlconstant_1_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_2_0/synth/pl_eth_10g_xlconstant_2_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_bit_sync.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_reset_sync.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b860/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/synth/gtwizard_ultrascale_v1_7_gthe4_channel.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/synth/pl_eth_10g_xxv_ethernet_0_0_gt_gthe4_channel_wrapper.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/synth/pl_eth_10g_xxv_ethernet_0_0_gt_gtwizard_gthe4.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/synth/pl_eth_10g_xxv_ethernet_0_0_gt_gtwizard_top.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/synth/pl_eth_10g_xxv_ethernet_0_0_gt.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_wrapper.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_top.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_axi4_lite_if_wrapper.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0/gtwizard_ultrascale_v1_7_gthe4_common.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0_gt_gthe4_common_wrapper.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_common_wrapper.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_ultrascale_rx_userclk.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/xxv_ethernet_v3_1_0/pl_eth_10g_xxv_ethernet_0_0_ultrascale_tx_userclk.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/6b0d/hdl/axi_crossbar_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xbar_0/synth/pl_eth_10g_xbar_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/9e81/hdl/axi_clock_converter_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/d394/hdl/axi_dwidth_converter_v2_1_vlsyn_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_us_0/synth/pl_eth_10g_auto_us_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_us_1/synth/pl_eth_10g_auto_us_1.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_0/synth/pl_eth_10g_auto_cc_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_us_2/synth/pl_eth_10g_auto_us_2.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_1/synth/pl_eth_10g_auto_cc_1.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/cba0/hdl/axi_mmu_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_s00_mmu_0/synth/pl_eth_10g_s00_mmu_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_s01_mmu_0/synth/pl_eth_10g_s01_mmu_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_s02_mmu_0/synth/pl_eth_10g_s02_mmu_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xbar_1/synth/pl_eth_10g_xbar_1.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_0/synth/pl_eth_10g_auto_ds_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_0/synth/pl_eth_10g_auto_pc_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_1/synth/pl_eth_10g_auto_ds_1.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_1/synth/pl_eth_10g_auto_pc_1.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_util_vector_logic_0_0/synth/pl_eth_10g_util_vector_logic_0_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_xlconcat_0_0/synth/pl_eth_10g_xlconcat_0_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/hdl/zynq_ultra_ps_e_v3_3_1.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/synth/pl_eth_10g_zynq_ultra_ps_e_0_0.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/synth/pl_eth_10g.v
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/hdl/pl_eth_10g_wrapper.v
    }
      rt::read_vhdl -lib lib_pkg_v1_0_2 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_fifo_v1_0_14 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_srl_fifo_v1_0_2 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib axi_datamover_v5_1_22 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/1e40/hdl/axi_datamover_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib axi_sg_v4_1_13 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd
      rt::read_vhdl -lib axi_dma_v7_1_21 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/ec2a/hdl/axi_dma_v7_1_vh_rfs.vhd
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/2985/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib fifo_generator_v13_2_5 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/276e/hdl/fifo_generator_v13_2_vhsyn_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_axi_dma_0_0/synth/pl_eth_10g_axi_dma_0_0.vhd
      /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ip/pl_eth_10g_rst_ps8_0_99M_0/synth/pl_eth_10g_rst_ps8_0_99M_0.vhd
    }
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/pl_eth_10g_hw/pl_eth_10g.srcs/sources_1/bd/pl_eth_10g/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top pl_eth_10g_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-53963-supersonic/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
