# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/supersonic/Lab/ZCU102-Ethernet/2019.2/pl_eth_10g/Hardware/constraints/constraints.xdc

# Block Designs: bd/pl_eth_10g/pl_eth_10g.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g || ORIG_REF_NAME==pl_eth_10g} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_axi_dma_0_0/pl_eth_10g_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_axi_dma_0_0 || ORIG_REF_NAME==pl_eth_10g_axi_dma_0_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_dma_rx_rst_0/pl_eth_10g_dma_rx_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_dma_rx_rst_0 || ORIG_REF_NAME==pl_eth_10g_dma_rx_rst_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_dma_tx_rst_0/pl_eth_10g_dma_tx_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_dma_tx_rst_0 || ORIG_REF_NAME==pl_eth_10g_dma_tx_rst_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_rx_data_fifo_0/pl_eth_10g_rx_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_rx_data_fifo_0 || ORIG_REF_NAME==pl_eth_10g_rx_data_fifo_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_rx_rst_n_0/pl_eth_10g_rx_rst_n_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_rx_rst_n_0 || ORIG_REF_NAME==pl_eth_10g_rx_rst_n_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_sfp_tx_dis_0/pl_eth_10g_sfp_tx_dis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_sfp_tx_dis_0 || ORIG_REF_NAME==pl_eth_10g_sfp_tx_dis_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_tx_data_fifo_0/pl_eth_10g_tx_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_tx_data_fifo_0 || ORIG_REF_NAME==pl_eth_10g_tx_data_fifo_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_tx_rst_n_0/pl_eth_10g_tx_rst_n_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_tx_rst_n_0 || ORIG_REF_NAME==pl_eth_10g_tx_rst_n_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_0_0/pl_eth_10g_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xlconstant_0_0 || ORIG_REF_NAME==pl_eth_10g_xlconstant_0_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_1_0/pl_eth_10g_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xlconstant_1_0 || ORIG_REF_NAME==pl_eth_10g_xlconstant_1_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xlconstant_2_0/pl_eth_10g_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xlconstant_2_0 || ORIG_REF_NAME==pl_eth_10g_xlconstant_2_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/pl_eth_10g_xxv_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xxv_ethernet_0_0 || ORIG_REF_NAME==pl_eth_10g_xxv_ethernet_0_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/pl_eth_10g_xxv_ethernet_0_0_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xxv_ethernet_0_0_gt || ORIG_REF_NAME==pl_eth_10g_xxv_ethernet_0_0_gt} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xbar_0/pl_eth_10g_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xbar_0 || ORIG_REF_NAME==pl_eth_10g_xbar_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_0/pl_eth_10g_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_us_0 || ORIG_REF_NAME==pl_eth_10g_auto_us_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_1/pl_eth_10g_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_us_1 || ORIG_REF_NAME==pl_eth_10g_auto_us_1} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_0/pl_eth_10g_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_cc_0 || ORIG_REF_NAME==pl_eth_10g_auto_cc_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_2/pl_eth_10g_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_us_2 || ORIG_REF_NAME==pl_eth_10g_auto_us_2} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_1/pl_eth_10g_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_cc_1 || ORIG_REF_NAME==pl_eth_10g_auto_cc_1} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_s00_mmu_0/pl_eth_10g_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_s00_mmu_0 || ORIG_REF_NAME==pl_eth_10g_s00_mmu_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_s01_mmu_0/pl_eth_10g_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_s01_mmu_0 || ORIG_REF_NAME==pl_eth_10g_s01_mmu_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_s02_mmu_0/pl_eth_10g_s02_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_s02_mmu_0 || ORIG_REF_NAME==pl_eth_10g_s02_mmu_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_axi_pl_ps_0/pl_eth_10g_axi_pl_ps_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_axi_pl_ps_0 || ORIG_REF_NAME==pl_eth_10g_axi_pl_ps_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xbar_1/pl_eth_10g_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xbar_1 || ORIG_REF_NAME==pl_eth_10g_xbar_1} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_0/pl_eth_10g_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_ds_0 || ORIG_REF_NAME==pl_eth_10g_auto_ds_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_0/pl_eth_10g_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_pc_0 || ORIG_REF_NAME==pl_eth_10g_auto_pc_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_1/pl_eth_10g_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_ds_1 || ORIG_REF_NAME==pl_eth_10g_auto_ds_1} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_1/pl_eth_10g_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_pc_1 || ORIG_REF_NAME==pl_eth_10g_auto_pc_1} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_ps_axi_periph_0/pl_eth_10g_ps_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_ps_axi_periph_0 || ORIG_REF_NAME==pl_eth_10g_ps_axi_periph_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_rst_ps8_0_99M_0/pl_eth_10g_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_rst_ps8_0_99M_0 || ORIG_REF_NAME==pl_eth_10g_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_util_vector_logic_0_0/pl_eth_10g_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_util_vector_logic_0_0 || ORIG_REF_NAME==pl_eth_10g_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_xlconcat_0_0/pl_eth_10g_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_xlconcat_0_0 || ORIG_REF_NAME==pl_eth_10g_xlconcat_0_0} -quiet] -quiet

# IP: bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/pl_eth_10g_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pl_eth_10g_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==pl_eth_10g_zynq_ultra_ps_e_0_0} -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_axi_dma_0_0/pl_eth_10g_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_axi_dma_0_0 || ORIG_REF_NAME==pl_eth_10g_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_axi_dma_0_0/pl_eth_10g_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_axi_dma_0_0 || ORIG_REF_NAME==pl_eth_10g_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/synth/pl_eth_10g_xxv_ethernet_0_0_gt_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/ip_0/synth/pl_eth_10g_xxv_ethernet_0_0_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_xxv_ethernet_0_0_gt || ORIG_REF_NAME==pl_eth_10g_xxv_ethernet_0_0_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/synth/pl_eth_10g_xxv_ethernet_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_xxv_ethernet_0_0 || ORIG_REF_NAME==pl_eth_10g_xxv_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/synth/pl_eth_10g_xxv_ethernet_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_xxv_ethernet_0_0 || ORIG_REF_NAME==pl_eth_10g_xxv_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/synth/pl_eth_10g_xxv_ethernet_0_0_exceptions.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_xxv_ethernet_0_0 || ORIG_REF_NAME==pl_eth_10g_xxv_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_xxv_ethernet_0_0/synth/pl_eth_10g_xxv_ethernet_0_0_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_0/pl_eth_10g_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_us_0 || ORIG_REF_NAME==pl_eth_10g_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_0/pl_eth_10g_auto_us_0_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_1/pl_eth_10g_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_us_1 || ORIG_REF_NAME==pl_eth_10g_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_1/pl_eth_10g_auto_us_1_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_0/pl_eth_10g_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_cc_0 || ORIG_REF_NAME==pl_eth_10g_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_0/pl_eth_10g_auto_cc_0_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_2/pl_eth_10g_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_us_2 || ORIG_REF_NAME==pl_eth_10g_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_us_2/pl_eth_10g_auto_us_2_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_1/pl_eth_10g_auto_cc_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_cc_1 || ORIG_REF_NAME==pl_eth_10g_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_cc_1/pl_eth_10g_auto_cc_1_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_0/pl_eth_10g_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_ds_0 || ORIG_REF_NAME==pl_eth_10g_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_0/pl_eth_10g_auto_ds_0_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_0/pl_eth_10g_auto_pc_0_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_1/pl_eth_10g_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_auto_ds_1 || ORIG_REF_NAME==pl_eth_10g_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_ds_1/pl_eth_10g_auto_ds_1_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_auto_pc_1/pl_eth_10g_auto_pc_1_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_rst_ps8_0_99M_0/pl_eth_10g_rst_ps8_0_99M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_rst_ps8_0_99M_0 || ORIG_REF_NAME==pl_eth_10g_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_rst_ps8_0_99M_0/pl_eth_10g_rst_ps8_0_99M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_rst_ps8_0_99M_0 || ORIG_REF_NAME==pl_eth_10g_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/pl_eth_10g_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/pl_eth_10g/ip/pl_eth_10g_zynq_ultra_ps_e_0_0/pl_eth_10g_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pl_eth_10g_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==pl_eth_10g_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/pl_eth_10g/pl_eth_10g_ooc.xdc
